project_name: autoquery
release:
  github:
    owner: thnxdev
    name: autoquery
brews:
  -
    install: bin.install "autoquery"
env:
  - CGO_ENABLED=0
builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - arm64
    - amd64
    - "386"
  goarm:
    - "6"
  dir: ./cmd/autoquery
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: autoquery
archives:
  -
    format: tar.gz
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
    files:
      - COPYING
      - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
